---
apiVersion: ddp.mayadata.io/v1alpha1
kind: Storage
metadata:
  name: magic-stor
  namespace: default
  annotations:
    storageprovisioner.ddp.mayadata.io/storageclass-name: csi-sc-opensdsplugin
    storageprovisioner.ddp.mayadata.io/csi-attacher-name: csi-opensdsplugin
spec:
  # provide appropriate value
  capacity: 1Gi
  # replace the node name with the node of your cluster
  nodeName: {{ node-name }}
